### ISSUE TITLE
Number Format Error in #AuthFragment

### ISSUE THREAD

**Issue by aryeahtyagi** [fortrade-studio/TikTok#4]
**Number Format wrong shows no message**

The Number Edit Text Field is showing no error if the number is in valid it is just showing a toast with no localized message for the user .

We Need to add some short of message to the phone Number textbox to be shown when their is error with the number.

Suggestion:
```diff
!  We Can use the EditText.setError("  message ") method to show error to an textbox if input is wrong
```

**Comment by blappdeveloper** [comment]
bug solved
