### ISSUE TITLE
BUG : INVALID OTP SHOWS INVALID PHONE NUMBER ERROR

### ISSUE THREAD

**Issue by aryeahtyagi** [fortrade-studio/TikTok#6]
### **BUG 👎🏻**

```diff
-When I Enter Invalid OTP in the otp box the app says invalid phone number message 
```
### HAVE A LOOK
![Screenshot_2021-05-30-13-48-07-106_com fortrade tiktok](https://user-images.githubusercontent.com/67866420/120097641-463e5780-c14f-11eb-8d98-97cc33343e9b.jpg)

**Comment by blappdeveloper** [comment]
fix
