### ISSUE TITLE
ENHANCEMENT : RESEND OTP SHOULD HAVE TIMER OF 1 MIN

### ISSUE THREAD

**Issue by aryeahtyagi** [fortrade-studio/TikTok#7]
### Resend Otp Should have a timer of  60 Sec which user have to wait before resending the otp again

> **Currently User don't have any wait time before sending the otp again  ,
 So we Should add a timer which will allow user to re-send Otp to the user only after 60 sec .**

**Comment by blappdeveloper** [comment]
working

**Comment by blappdeveloper** [comment]
complete
